from .dashboard import DashboardView
from .models import *
from .modelselection import *
from .person import PersonView
from .setup import SetupView
from .dataset import DatasetView
from .config import ConfigView
from .webhook import WebhookView
from .datasetAnalytics import DatasetAnalyticsView
from .deviceAssignment import AssignDeviceView
from .dashboard_plotly import *