# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# from here on its different
input_boolean:
  binary_01:
    name: Bin 1
  binary_02:
    name: Bin 2
  binary_03:
    name: Bin 3
  binary_04:
    name: Bin 4
input_select:
  cat_1:
    name: Cat 1
    options:
      - c11
      - c12
      - c13
  cat_2:
    name: Cat 2
    options:
      - c21
      - c22
      - c23
      - c24

input_number:
  num_1:
    name: Num 1
    initial: 30
    min: 0
    max: 100
  num_2:
    name: Num 2
    initial: 30
    min: -100
    max: 100
