# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# from here on its different
input_boolean:
  binary_01:
    name: Bin 1
  binary_02:
    name: Bin 2
  binary_03:
    name: Bin 3
  binary_04:
    name: Bin 4
  binary_05:
    name: Bin 5
  binary_06:
    name: Bin 6
  binary_07:
    name: Bin 7
  binary_08:
    name: Bin 8
  binary_09_very_long_unecessary_entity_id_that_is_be_automatically_assigned:
    name: Bin 9
  binary_10:
    name: Bin 10
  binary_11:
    name: Bin 11
  binary_12:
    name: Bin 12
  binary_13:
    name: Bin 13
  binary_14:
    name: Bin 14
  binary_15:
    name: Bin 15
  binary_16:
    name: Bin 16
  binary_17:
    name: Bin 17
  binary_18:
    name: Bin 18
  binary_19:
    name: Bin 19
  binary_20:
    name: Bin 20
input_select:
  cat_1:
    name: Cat 1
    options:
      - c11
      - c12
  cat_2:
    name: Cat 2
    options:
      - c21
      - c22
      - c23
  cat_3:
    name: Cat 3
    options:
      - c31
      - c32
      - c33
      - c34
  cat_4:
    name: Cat 4
    options:
      - c41
      - c32
      - c33
      - c44
      - c45

input_number:
  num_1:
    name: Num 1
    initial: 30
    min: 0
    max: 100
  num_2:
    name: Num 2
    initial: 30
    min: -100
    max: 100
