# Generated by Django 3.1.2 on 2020-10-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201026_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_polling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='poll_interval',
            field=models.CharField(default='10m', max_length=10),
        ),
    ]
