# Generated by Django 3.1.2 on 2020-10-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_server_hass_db_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='hass_db_path',
        ),
    ]
