# Generated by Django 3.1.2 on 2020-10-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_server_hass_db_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='state',
        ),
    ]
