# Generated by Django 3.1.2 on 2020-10-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_device_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
    ]
