# Generated by Django 3.1.2 on 2020-10-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_device_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='predicted_location',
        ),
    ]
