# Generated by Django 3.1.2 on 2020-10-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201028_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='path_to_folder',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
