# Generated by Django 3.1.2 on 2020-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201028_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
