# Generated by Django 3.1.2 on 2020-10-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20201030_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='backend.person'),
        ),
    ]
