# Generated by Django 3.1.2 on 2020-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201030_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hass_comp_installed',
            field=models.BooleanField(default=False),
        ),
    ]
