# Generated by Django 3.1.3 on 2020-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_server_zero_conf_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='poll_service_pid',
            field=models.IntegerField(null=True),
        ),
    ]
