# Generated by Django 3.1.3 on 2020-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_server_poll_service_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='logging',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='person',
        ),
    ]
