# Generated by Django 3.1.3 on 2020-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20201104_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='webhook_count',
            field=models.IntegerField(default=0),
        ),
    ]
