name: 'Publish edge'
on:
  workflow_dispatch:

jobs:
  build_alpine:
    name: Publish alpine builds for amd64 and (i386)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: tcsvn/builder@master
      with:
        args: |
          --amd64 \
          --file build/prod/Dockerfile \
          --no-cache \
          --version latest \
          --target /data

  build_ubuntu:
    name: Publish ubuntu build for armv7, (armhf) and aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: tcsvn/builder@master
      with:
        args: |
          --armv7 \
          --aarch64 \
          --file build/prod_ubuntu/Dockerfile \
          --no-cache \
          --version latest \
          --target /data
