name: "Publish edge"
on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build_alpine:
    name: Publish alpine builds for amd64 and i386
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Link build and config.yaml
        run: ln -s build/prod/build.yaml build.yaml && ln -s build/prod/config.yaml config.yaml
      - name: Publish
        uses: tcsvn/builder@master
        with:
          args: |
            --amd64 \
            --i386 \
            --file build/prod/Dockerfile \
            --no-cache \
            --version latest \
            --target /data

  build_debian:
    name: Publish debian build for armv7, (armhf) and aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Link build and config.yaml
        run: ln -s build/prod/build.yaml build.yaml && ln -s build/prod/config.yaml config.yaml
      - name: Publish
        uses: tcsvn/builder@master
        with:
          args: |
            --armv7 \
            --aarch64 \
            --file build/prod/Dockerfile_debian \
            --no-cache \
            --version latest \
            --target /data
