name: 'Build ubuntu base'
on:
  workflow_dispatch:

jobs:
  build:
    name: Build ubuntu base armv7
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: tcsvn/builder@master
      with:
        args: |
          --armv7 \
          --file build/prod_ubuntu/Dockerfile.base \
          --target /data/build/prod_ubuntu
  build:
    name: Build ubuntu base armhf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: tcsvn/builder@master
      with:
        args: |
          --aarch64 \
          --file build/prod_ubuntu/Dockerfile.base \
          --target /data/build/prod_ubuntu
  build:
    name: Build ubuntu base aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: tcsvn/builder@master
      with:
        args: |
          --armhf \
          --file build/prod_ubuntu/Dockerfile.base \
          --target /data/build/prod_ubuntu